"""init db

Revision ID: 57a5a84e79d0
Revises: 
Create Date: 2025-05-11 21:29:06.925736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57a5a84e79d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('siren_number', sa.String(), nullable=True),
    sa.Column('nic_number', sa.String(), nullable=True),
    sa.Column('legal_form', sa.String(), nullable=True),
    sa.Column('ape_code', sa.String(), nullable=True),
    sa.Column('ape_label', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('department_number', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('trade_name', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('deregistration_date', sa.Date(), nullable=True),
    sa.Column('closing_date_2018_1', sa.Date(), nullable=True),
    sa.Column('revenue_2018_1', sa.Float(), nullable=True),
    sa.Column('turnover_2018_1', sa.Float(), nullable=True),
    sa.Column('closing_date_2018_2', sa.Date(), nullable=True),
    sa.Column('revenue_2018_2', sa.Float(), nullable=True),
    sa.Column('turnover_2018_2', sa.Float(), nullable=True),
    sa.Column('closing_date_2018_3', sa.Date(), nullable=True),
    sa.Column('revenue_2018_3', sa.Float(), nullable=True),
    sa.Column('turnover_2018_3', sa.Float(), nullable=True),
    sa.Column('closing_date_2019_1', sa.Date(), nullable=True),
    sa.Column('revenue_2019_1', sa.Float(), nullable=True),
    sa.Column('turnover_2019_1', sa.Float(), nullable=True),
    sa.Column('closing_date_2019_2', sa.Date(), nullable=True),
    sa.Column('revenue_2019_2', sa.Float(), nullable=True),
    sa.Column('turnover_2019_2', sa.Float(), nullable=True),
    sa.Column('closing_date_2019_3', sa.Date(), nullable=True),
    sa.Column('revenue_2019_3', sa.Float(), nullable=True),
    sa.Column('turnover_2019_3', sa.Float(), nullable=True),
    sa.Column('closing_date_2020_1', sa.Date(), nullable=True),
    sa.Column('revenue_2020_1', sa.Float(), nullable=True),
    sa.Column('turnover_2020_1', sa.Float(), nullable=True),
    sa.Column('closing_date_2020_2', sa.Date(), nullable=True),
    sa.Column('revenue_2020_2', sa.Float(), nullable=True),
    sa.Column('turnover_2020_2', sa.Float(), nullable=True),
    sa.Column('closing_date_2020_3', sa.Date(), nullable=True),
    sa.Column('revenue_2020_3', sa.Float(), nullable=True),
    sa.Column('turnover_2020_3', sa.Float(), nullable=True),
    sa.Column('closing_date_2021_1', sa.Date(), nullable=True),
    sa.Column('revenue_2021_1', sa.Float(), nullable=True),
    sa.Column('turnover_2021_1', sa.Float(), nullable=True),
    sa.Column('closing_date_2021_2', sa.Date(), nullable=True),
    sa.Column('revenue_2021_2', sa.Float(), nullable=True),
    sa.Column('turnover_2021_2', sa.Float(), nullable=True),
    sa.Column('closing_date_2021_3', sa.Date(), nullable=True),
    sa.Column('revenue_2021_3', sa.Float(), nullable=True),
    sa.Column('turnover_2021_3', sa.Float(), nullable=True),
    sa.Column('closing_date_2022_1', sa.Date(), nullable=True),
    sa.Column('revenue_2022_1', sa.Float(), nullable=True),
    sa.Column('turnover_2022_1', sa.Float(), nullable=True),
    sa.Column('closing_date_2022_2', sa.Date(), nullable=True),
    sa.Column('revenue_2022_2', sa.Float(), nullable=True),
    sa.Column('turnover_2022_2', sa.Float(), nullable=True),
    sa.Column('closing_date_2022_3', sa.Date(), nullable=True),
    sa.Column('revenue_2022_3', sa.Float(), nullable=True),
    sa.Column('turnover_2022_3', sa.Float(), nullable=True),
    sa.Column('closing_date_2023_1', sa.Date(), nullable=True),
    sa.Column('revenue_2023_1', sa.Float(), nullable=True),
    sa.Column('turnover_2023_1', sa.Float(), nullable=True),
    sa.Column('closing_date_2023_2', sa.Date(), nullable=True),
    sa.Column('revenue_2023_2', sa.Float(), nullable=True),
    sa.Column('turnover_2023_2', sa.Float(), nullable=True),
    sa.Column('closing_date_2023_3', sa.Date(), nullable=True),
    sa.Column('revenue_2023_3', sa.Float(), nullable=True),
    sa.Column('turnover_2023_3', sa.Float(), nullable=True),
    sa.Column('industry_sector', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('website', sa.String(length=3000), nullable=True),
    sa.Column('reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('instagram', sa.String(length=10000), nullable=True),
    sa.Column('facebook', sa.String(length=3000), nullable=True),
    sa.Column('twitter', sa.String(length=3000), nullable=True),
    sa.Column('linkedin', sa.String(length=3000), nullable=True),
    sa.Column('youtube', sa.String(length=3000), nullable=True),
    sa.Column('email', sa.String(length=3000), nullable=True),
    sa.Column('scraping_date', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('last_processing_date', sa.Date(), nullable=True),
    sa.Column('number_of_employee', sa.Integer(), nullable=True),
    sa.Column('company_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_city', 'companies', ['city'], unique=False)
    op.create_index('ix_companies_city_industry_sector', 'companies', ['city', 'industry_sector'], unique=False)
    op.create_index('ix_companies_city_industry_sector_legal_form', 'companies', ['city', 'industry_sector', 'legal_form'], unique=False)
    op.create_index('ix_companies_city_legal_form', 'companies', ['city', 'legal_form'], unique=False)
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=False)
    op.create_index('ix_companies_email', 'companies', ['email'], unique=False)
    op.create_index('ix_companies_facebook', 'companies', ['facebook'], unique=False)
    op.create_index('ix_companies_industry_sector', 'companies', ['industry_sector'], unique=False)
    op.create_index('ix_companies_industry_sector_legal_form', 'companies', ['industry_sector', 'legal_form'], unique=False)
    op.create_index('ix_companies_industry_sector_number_of_employee', 'companies', ['industry_sector', 'number_of_employee'], unique=False)
    op.create_index('ix_companies_instagram', 'companies', ['instagram'], unique=False)
    op.create_index('ix_companies_legal_form', 'companies', ['legal_form'], unique=False)
    op.create_index('ix_companies_linkedin', 'companies', ['linkedin'], unique=False)
    op.create_index('ix_companies_number_of_employee', 'companies', ['number_of_employee'], unique=False)
    op.create_index('ix_companies_phone_number', 'companies', ['phone_number'], unique=False)
    op.create_index('ix_companies_region', 'companies', ['region'], unique=False)
    op.create_index('ix_companies_region_city', 'companies', ['region', 'city'], unique=False)
    op.create_index('ix_companies_region_city_industry_sector', 'companies', ['region', 'city', 'industry_sector'], unique=False)
    op.create_index('ix_companies_region_city_industry_sector_legal_form', 'companies', ['region', 'city', 'industry_sector', 'legal_form'], unique=False)
    op.create_index('ix_companies_region_city_legal_form', 'companies', ['region', 'city', 'legal_form'], unique=False)
    op.create_index('ix_companies_region_industry_sector', 'companies', ['region', 'industry_sector'], unique=False)
    op.create_index('ix_companies_region_industry_sector_legal_form', 'companies', ['region', 'industry_sector', 'legal_form'], unique=False)
    op.create_index('ix_companies_region_legal_form', 'companies', ['region', 'legal_form'], unique=False)
    op.create_index('ix_companies_siren_number', 'companies', ['siren_number'], unique=False)
    op.create_index('ix_companies_twitter', 'companies', ['twitter'], unique=False)
    op.create_index('ix_companies_website', 'companies', ['website'], unique=False)
    op.create_index('ix_companies_youtube', 'companies', ['youtube'], unique=False)
    op.create_table('leaders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siren', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('gestion_number', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('usage_name', sa.String(), nullable=True),
    sa.Column('pseudo', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(length=3000), nullable=True),
    sa.Column('legal_form', sa.String(), nullable=True),
    sa.Column('id_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leader_company_name', 'leaders', ['company_name'], unique=False)
    op.create_index('idx_leader_first_name', 'leaders', ['first_name'], unique=False)
    op.create_index('idx_leader_last_name', 'leaders', ['last_name'], unique=False)
    op.create_index('idx_leader_role', 'leaders', ['role'], unique=False)
    op.create_index('idx_leader_siren', 'leaders', ['siren'], unique=False)
    op.create_table('config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('last_reset_quota_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_city_name', 'city', ['name'], unique=False)
    op.create_table('industry_sector',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_industry_sector_name', 'industry_sector', ['name'], unique=False)
    op.create_table('legal_form',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_form_name', 'legal_form', ['name'], unique=False)
    op.create_table('region',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_region_name', 'region', ['name'], unique=False)
    op.create_table('user_quota',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('quota_allocated', sa.Integer(), nullable=True),
    sa.Column('quota_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_quota_quota_allocated', 'user_quota', ['quota_allocated'], unique=False)
    op.create_index('ix_user_quota_quota_used', 'user_quota', ['quota_used'], unique=False)
    op.create_index('ix_user_quota_user_id', 'user_quota', ['user_id'], unique=False)
    op.create_table('user_company_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_DONE', 'TO_DO', 'DONE', name='status'), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_company_status_company_id', 'user_company_status', ['company_id'], unique=False)
    op.create_index('ix_user_company_status_user_id', 'user_company_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_company_status_user_id', table_name='user_company_status')
    op.drop_index('ix_user_company_status_company_id', table_name='user_company_status')
    op.drop_table('user_company_status')
    op.drop_index('ix_user_quota_user_id', table_name='user_quota')
    op.drop_index('ix_user_quota_quota_used', table_name='user_quota')
    op.drop_index('ix_user_quota_quota_allocated', table_name='user_quota')
    op.drop_table('user_quota')
    op.drop_index('ix_region_name', table_name='region')
    op.drop_table('region')
    op.drop_index('ix_legal_form_name', table_name='legal_form')
    op.drop_table('legal_form')
    op.drop_index('ix_industry_sector_name', table_name='industry_sector')
    op.drop_table('industry_sector')
    op.drop_index('ix_city_name', table_name='city')
    op.drop_table('city')
    op.drop_table('config')
    op.drop_index('idx_leader_siren', table_name='leaders')
    op.drop_index('idx_leader_role', table_name='leaders')
    op.drop_index('idx_leader_last_name', table_name='leaders')
    op.drop_index('idx_leader_first_name', table_name='leaders')
    op.drop_index('idx_leader_company_name', table_name='leaders')
    op.drop_table('leaders')
    op.drop_index('ix_companies_youtube', table_name='companies')
    op.drop_index('ix_companies_website', table_name='companies')
    op.drop_index('ix_companies_twitter', table_name='companies')
    op.drop_index('ix_companies_siren_number', table_name='companies')
    op.drop_index('ix_companies_region_legal_form', table_name='companies')
    op.drop_index('ix_companies_region_industry_sector_legal_form', table_name='companies')
    op.drop_index('ix_companies_region_industry_sector', table_name='companies')
    op.drop_index('ix_companies_region_city_legal_form', table_name='companies')
    op.drop_index('ix_companies_region_city_industry_sector_legal_form', table_name='companies')
    op.drop_index('ix_companies_region_city_industry_sector', table_name='companies')
    op.drop_index('ix_companies_region_city', table_name='companies')
    op.drop_index('ix_companies_region', table_name='companies')
    op.drop_index('ix_companies_phone_number', table_name='companies')
    op.drop_index('ix_companies_number_of_employee', table_name='companies')
    op.drop_index('ix_companies_linkedin', table_name='companies')
    op.drop_index('ix_companies_legal_form', table_name='companies')
    op.drop_index('ix_companies_instagram', table_name='companies')
    op.drop_index('ix_companies_industry_sector_number_of_employee', table_name='companies')
    op.drop_index('ix_companies_industry_sector_legal_form', table_name='companies')
    op.drop_index('ix_companies_industry_sector', table_name='companies')
    op.drop_index('ix_companies_facebook', table_name='companies')
    op.drop_index('ix_companies_email', table_name='companies')
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.drop_index('ix_companies_city_legal_form', table_name='companies')
    op.drop_index('ix_companies_city_industry_sector_legal_form', table_name='companies')
    op.drop_index('ix_companies_city_industry_sector', table_name='companies')
    op.drop_index('ix_companies_city', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
