name: Build and Push Docker Image

on:
  push:
    branches:
      - develop # dev trigger (automatic)
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      manual_tag:
        description: 'Optional manual tag to override versioning'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  dev_build:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      environment: dev
      manual_tag: ${{ inputs.manual_tag }}
    secrets: inherit

  prod_build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name != 'pull_request' }}
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      environment: prod
      manual_tag: ${{ github.event.inputs.manual_tag }}
    secrets: inherit
