name: Build and Push ImageS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
      NEXUS_DOCKER_URL: ${{ secrets.NEXUS_DOCKER_URL }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      DOCKER_DATA_MODEL_NAME: infocompanies-data-model-postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - if: ${{ inputs.environment != 'prod' && inputs.environment != 'dev' }}
        name: Validate environment input
        run: |
          echo "Error: 'environment' must be 'dev' or 'prod'."
          exit 1
      
      - if: ${{ inputs.environment == 'dev' }}
        name: Login to Nexus native port for pulling CSVs
        run: |
          echo "${NEXUS_PASSWORD}" | docker login "${NEXUS_URL}" -u "${NEXUS_USERNAME}" --password-stdin
          ./scripts/pull-csv.sh
          docker logout "${NEXUS_URL}"

      - name: Build prefilled Postgres image
        run: |
          DOCKER_TAG=$(date +%Y%m%d%H%M%S)

          if [ "${{ inputs.environment }}" == "dev" ]; then
            DOCKERFILE="dev.Dockerfile"
          else
            DOCKERFILE="prod.Dockerfile"
          fi

          IMAGE="${NEXUS_URL}/${DOCKER_DATA_MODEL_NAME}-${{ inputs.environment }}:${DOCKER_TAG}"
          docker build -f "${DOCKERFILE}" -t $IMAGE .

          echo "${NEXUS_PASSWORD}" | docker login "${NEXUS_DOCKER_URL}" -u "${NEXUS_USERNAME}" --password-stdin
          docker push $IMAGE
          docker logout "${NEXUS_DOCKER_URL}"


      - name: Clean up Docker resources
        run: |
          docker rm -f "${DOCKER_DATA_MODEL_NAME}" || true
          docker volume rm pgdata || true
          docker system prune -f
